# User config
author: "Aran Irahan"
tagline: "Android Developer"
description: "Lets learn every day until die"
keywords: "android, life, my project"
email: "aranirahan@gmail.com"
article: "https://aranlearn.github.io/dailylearn"
linkedin: "https://www.linkedin.com/in/aranirahan"
twitter: "https://twitter.com/aranirahan"
github: "https://github.com/aranirahan"

# Site config
baseurl: "https://aranirahan.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
